theme: jekyll-theme-minimal
title: Test to see if it works
description: still test
show_downloads: True
navigation:
  - title: Test
    url: https://www.google.com/
  - title: Test encore
    url: example.md
